[theme]
# 明るい背景に合う主要カラー（例：ボタン、強調表示）
primaryColor="#0000FF"  # 鮮やかな青（newpeaceの青）

# アプリケーション全体の背景色
backgroundColor="#FFFFFF" # 純粋な白

# サイドバーや一部コンポーネントの背景色
secondaryBackgroundColor="#F8F8F8" # わずかにグレーがかった白

# テキストの標準色 (明るい背景に合うように暗くする)
textColor="#333333" # 濃いグレー

# フォントの設定（Streamlitでサポートされているもの）
font="sans serif"
