[theme]
# ボタン、リンク、強調表示のメインカラー（バナスコのアクセントカラー）
primaryColor="#00E676"  # 鮮やかなグリーン（精密機器のLED表示などをイメージ）

# アプリケーション全体の背景色
backgroundColor="#121212" # 非常に暗いグレー（ほぼ黒に近い）

# サイドバーや一部コンポーネントの背景色
secondaryBackgroundColor="#1E1E1E" # 背景より少し明るいグレー

# テキストの標準色
textColor="#E0E0E0" # 明るいグレー

# フォントの設定（Streamlitでサポートされているもの）
font="sans serif"
