# .streamlit/secrets.toml

# 1) OpenAI の API キー
OPENAI_API_KEY = "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"

# 2) Firebase Authentication 用 Web API キー
FIREBASE_WEB_API_KEY = "AIzaSyAflp1vqSA21sSYihZDTpje-MB1mCALxBs"

# 3) Firestore 操作用 プロジェクトID
FIREBASE_PROJECT_ID_ADMIN = "banasuko-auth"

# 4) 管理者用 サービスアカウント秘密鍵
FIREBASE_PRIVATE_KEY_ADMIN = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCz55fJ9fJ9Lw6d0/4blxc0Crj4nYbsVmPyH/IouiAA2kVl0uZMBAZ4Ori/LUMJKqjbWbO2jioW6Ra2HfczEXjQU0JVZUGuCGO5JTxMHGBvd5zpoLQSBBcckLCMmtcC5SctYyka3CRrmqzmKn2SqtAa4u+57zVduYl+jIlySzKMyVzsVkEMrHxv2i94J3TLLt3ZZ+Y5R1Fm3FMXDVNeXs7bTADThBUJBJAGVgZw9t5gjOVXF/s0PuOZY/DAAtAMbhL/XnXYTomfJNNaPTzMOnfXDwdeb45fEdRK2+rerQzbam1PWWxtzKG4MHkk36GzE92hS938xfKpv62p5YZZKBI1AgMBAAECggEAG2SpNSRQ/wS6SgfsilDwRIlZbum1kKj64PRCUDc/BkI2DPIXBP4b6hSu6tU+ftfTDEtVVPfCquhk/+gCKvF/HuF+mTgozxIR9TAZRVGQ0Yg6CUzh/lhHGJ9jcpVlJdi0pXGS4bchiIztxMI1iq6dr2pcrEgjLRlCOVW23ANdOBhzZHPy8+APE//SSWHjJCW3+mJLt6VzcKJV+R+V1RQzuQDWf51w09kG9l1iZzkIgj4UGWW17AT9TGfMKotSY1xbK7Au3DpF24V5C+fSEkayqBSHGYHhGO3WeZ15QDOIJPX4itJqJIuDrWdWCMJMYuODJe1840ypvTi9LQrrjLRIgQKBgQDvDIYkkxH4O6gA8CrzGku+3h0KXRmDDWGihL+kgV+q+R+gLeLt6YKxnxaJ+q0ofLAzSCRHomGAB3NCmjJyOtQPDmvCjR3Tw2SVKWHleL7VtEXnDK/toazfVx/pYVATIJ46GRXMlIMCOnJgXNKSKKhjndBa3DWh4ivs1YM5WCHB1QKBgQDAqWr/uLY5SwfR48wPBGt32BAIKnHP8BlRVSFas5ck+zkJpKFsdUWc2P0F39EXxzehN55EDy+trIpvVphXFHZRNaPaGPTiJGt+XfxBcNzP21W7AuOa0ZXrctMzSs4TFrZoMUnVY7LzvZg/ANcUy4Gdbikd4HdadD25wTfUFM7e4QKBgQCzhlJPsWuzYwn++l8nBz6PbzucBuMb+rayWMOcBdUVD9bictOUHOQcBP/mS64zU8D4IlusuJRElFPJVwg/pVKQpCHlkBkwafNl2hg9P3sB/0roBC0zZ1HuwP2kRYLfeoWZ2DD43SeuSrqPB+bUAVjEx0Yslmho1PRr/sV4EWn4qQKBgH0J9328Pdf1UD/yni9o6O7A9ba3BWK1K1lT7O/W+tNvkNcnV/TyL5naYmz7k9Lg4sPpOvhk+sa24qncA8cQarHOJGeaJuTWSkWbbepy+3yTl5JmD54dRDWpMlVpyVEuPnhk9MxfhncWp8bMHstKQPcR1fGkCxJTuvPh6P/l+VVBAoGBAN3tkTGM3b8dmcyWWeURNt3m4IyVUrJQBep7hScJed4MCwjLzHpYqsfpXpQDSpPPEwxNXiE+FcsfDEPBua2n/Fim1VKYadu1lFsjrnnVIf2rUa4E+/CVb1wAWMVQxy83sMvl0VPgYuSTMjJ9ISy3ucfCW+w0gslmNvowoMZft6L4
-----END PRIVATE KEY-----"""

# 5) 管理者用 クライアントメール
FIREBASE_CLIENT_EMAIL_ADMIN = "firebase-adminsdk-fbsvc@banasuko-auth.iam.gserviceaccount.com"
