# .streamlit/secrets.toml

# 1) OpenAI の API キー
OPENAI_API_KEY = "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"

# 2) Firebase Authentication 用 Web API キー
FIREBASE_WEB_API_KEY = "AIzaSyAflp1vqSA21sSYihZDTpje-MB1mCALxBs"

# 3) Firestore 操作用 プロジェクトID
FIREBASE_PROJECT_ID_ADMIN = "banasuko-auth"

# 4) 管理者用 サービスアカウント秘密鍵
FIREBASE_PRIVATE_KEY_ADMIN = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCl0Wc27ox1f4EDT98KXblqcbzN3BVQkqERRE0jql0d6s5JjmOFh1mO8W/cG0NreX50uC/kN+nof76psqszyw/+q5LnG6S5XLHWDl8bx9nK+yT37LraszpsHJ/cf/MVdBPDhwUaXh3uylLInfPenoj8NIBE8QRwsDU2Bl9L/H61SdLFpm1mBJ/EJfpxh1Yg7alajsHgpHlwflMwOU2Jq5aE+zPgvSViOEloq0iTHGRXLWwVz6iF64bodvdPJHiEy+0+9gvug70BLL7tInpE93AoUoqlwwV5p2YbdhSG3ispenGvvgbPuLgPy9ipCDn/RLcFxQ8jzXZxG3uywok18SbyFVAgMBAAECggIAAmcBxVB4dX1W66rdEuPfu1SRhTQClQvCzKK+MV2XAsdznnKo08+rNl94Unk5A0E5O0DcY7ogG2gj7xK6jf1kaTrjCpJmIbe0TYIQNybPACopP802ZOXDuUEGr6UBrT6zCWotavhKOAXcp8uCon+OgYTrNNR/GXjcFH/MIqgyV8MNDEruRtuNTKAxM4EfIRvmyRUZ4csfoAQAZfSC1X5+vf1jVSTLQC8HSfACy/zgKC6NfqJrt8dBBEBjsYe1P3QFqslrjx9segUe/q+nCc+Fsmm9mL48PFu++fLUKi5OhSZIRFXni+g+kJCoIHvWEEB6EAVLEcsoEXdB+wBEyMdTjAwKBgQDXnrq6rmlGJ5gPoQsqEQguSvez7nqPn
-----END PRIVATE KEY-----"""

# 5) 管理者用 クライアントメール
FIREBASE_CLIENT_EMAIL_ADMIN = "firebase-adminsdk-fbsvc@banasuko-auth.iam.gserviceaccount.com"
