# .streamlit/secrets.toml

# 1) OpenAI の API キー
OPENAI_API_KEY = "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"

# 2) Firebase Authentication 用 Web API キー
FIREBASE_WEB_API_KEY = "AIzaSyAflp1vqSA21sSYihZDTpje-MB1mCALxBs"

# 3) Firestore 操作用 プロジェクトID
FIREBASE_PROJECT_ID_ADMIN = "banasuko-auth"

# 4) 管理者用 サービスアカウント秘密鍵
FIREBASE_PRIVATE_KEY_ADMIN = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCl0Wc27ox1f4ED
T98KXblqcbzN3BVQkqERRE0jql0d6s5JjmOFh1mO8W/cG0NreX50uC/kN+nof76p
sqszyw/+q5LnG6S5XLHWDl8bx9nK+yT37LraszpsHJ/cf/MVdBPDhwUaXh3uylLI
nfPenoj8NIBE8QRwsDU2Bl9L/H61SdLFpm1mBJ/EJfpxh1Yg7alajsHgpHlwflMwO
U2Jq5aE+zPgvSViOEloq0iTHGRXLWwVz6iF64bodvdPJHiEy+0+9gvug70BLL7tI
npE93AoUoqlwwV5p2YbdhSG3ispenGvvgbPuLgPy9ipCDn/RLcFxQ8jzXZxG3uywo
k18SbyFVAgMBAAECggIAAmcBxVB4dX1W66rdEuPfu1SRhTQClQvCzKK+MV2XAsdz
nnKo08+rNl94Unk5A0E5O0DcY7ogG2gj7xK6jf1kaTrjCpJmIbe0TYIQNybPACopP
802ZOXDuUEGr6UBrT6zCWotavhKOAXcp8uCon+OgYTrNNR/GXjcFH/MIqgyV8MNd
EruRtuNTKAxM4EfIRvmyRUZ4csfoAQAZfSC1X5+vf1jVSTLQC8HSfACy/zgKC6Nf
qJrt8dBBEBjsYe1P3QFqslrjx9segUe/q+nCc+Fsmm9mL48PFu++fLUKi5OhSZIR
FXni+g+kJCoIHvWEEB6EAVLEcsoEXdB+wBEyMdTjAwKBgQDXnrq6rmlGJ5gPoQsq
EQguSvez7nqPn3txxyfzNFy1docdKHCq1bttjy+8+IdayUaDfwYvD/LrOc2dk7k+
Zl7UkWeuj2J0T37g7kooUBh9l2EUpxupP9Z3ArGN13VnScfThUUXcJoC13E0paO2
D6d1W07Jt0rg2lAYYU7dNHrGpwKBgQDE3w9puHJatMBrbw3kGFOIM9qtg3mpebw0
EOx6lQTpWNUe05fFKGZ/MPOx1qXhYWk4wvzfeqbaqKBpNM1rI58fbgEcmzc7OgnW
nzeaoqh2HzsII3J07w1QANtA8OHy4VN8L5muTxhOLASYWtpWl/8YsKMq9his/VbRC
rLmVrSHTowKBgEyg6aXMtDctfRoY1rnlga3KEMwOddozCJEAAU+qjUQkUpJnO9tK
yCiAmauj+56lJ302GIGDPoagbVWSGWR2xz7uShW8eXXyhpnztcEr7fg8Y1EOroLw
4Aw9ldJd/yhtDSo8E7jn2KQn4uCd+VeLqqzHfXGsxVyx2YNAmeF9dCDDAoGAdbUo
cf1l4fXQVmu/0nD5AKaASN4jD8FJVZgIzAHtPddvFU9NnwPYxJNwIRRFecvULavn
npXaf7HyF7GE1sKlLqm8LGx9ylmbNGzFgh9eucFSejs3Y9LKEttwPBPKBH3UfJu5N
nw7zaUnINY+cm8mlLA3wgO9DMasHDVVoQW/14DCECgYAgCbpjC6dgRvmAfV2OiPyf
W7ScnUXnlUtXBFliMaAafuM4cZ4ci3wBjsQmv0Wed9oIQiFZhTxT3MYWzUIMZsau
Ct+HAjLWRdZ/PofoScMpavFenO4H3bqpWLsZnRxin/3mxOChMx1uuEhF981ZUSD4
XXGcTVfNa8SdOiW6WZc85Q==
-----END PRIVATE KEY-----"""

# 5) 管理者用 クライアントメール
FIREBASE_CLIENT_EMAIL_ADMIN = "firebase-adminsdk-fbsvc@banasuko-auth.iam.gserviceaccount.com"